/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdoruRouteImport } from './routes/idoru'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as MediaEmpireRouteImport } from './routes/media-empire'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ApiSsoConsumeRouteImport } from './routes/api/sso/consume'
import { Route as ApiSsoLoginRouteImport } from './routes/api/sso/login'
import { Route as ApiSsoLogoutRouteImport } from './routes/api/sso/logout'
import { Route as ApiSsoProfileRouteImport } from './routes/api/sso/profile'
import { Route as ApiSsoSessionRouteImport } from './routes/api/sso/session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdoruRoute = IdoruRouteImport.update({
  id: '/idoru',
  path: '/idoru',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaEmpireRoute = MediaEmpireRouteImport.update({
  id: '/media-empire',
  path: '/media-empire',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoConsumeRoute = ApiSsoConsumeRouteImport.update({
  id: '/api/sso/consume',
  path: '/api/sso/consume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoLoginRoute = ApiSsoLoginRouteImport.update({
  id: '/api/sso/login',
  path: '/api/sso/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoLogoutRoute = ApiSsoLogoutRouteImport.update({
  id: '/api/sso/logout',
  path: '/api/sso/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoProfileRoute = ApiSsoProfileRouteImport.update({
  id: '/api/sso/profile',
  path: '/api/sso/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoSessionRoute = ApiSsoSessionRouteImport.update({
  id: '/api/sso/session',
  path: '/api/sso/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/idoru': typeof IdoruRoute
  '/logout': typeof LogoutRoute
  '/media-empire': typeof MediaEmpireRoute
  '/menu': typeof MenuRoute
  '/api/sso/consume': typeof ApiSsoConsumeRoute
  '/api/sso/login': typeof ApiSsoLoginRoute
  '/api/sso/logout': typeof ApiSsoLogoutRoute
  '/api/sso/profile': typeof ApiSsoProfileRoute
  '/api/sso/session': typeof ApiSsoSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/idoru': typeof IdoruRoute
  '/logout': typeof LogoutRoute
  '/media-empire': typeof MediaEmpireRoute
  '/menu': typeof MenuRoute
  '/api/sso/consume': typeof ApiSsoConsumeRoute
  '/api/sso/login': typeof ApiSsoLoginRoute
  '/api/sso/logout': typeof ApiSsoLogoutRoute
  '/api/sso/profile': typeof ApiSsoProfileRoute
  '/api/sso/session': typeof ApiSsoSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/idoru': typeof IdoruRoute
  '/logout': typeof LogoutRoute
  '/media-empire': typeof MediaEmpireRoute
  '/menu': typeof MenuRoute
  '/api/sso/consume': typeof ApiSsoConsumeRoute
  '/api/sso/login': typeof ApiSsoLoginRoute
  '/api/sso/logout': typeof ApiSsoLogoutRoute
  '/api/sso/profile': typeof ApiSsoProfileRoute
  '/api/sso/session': typeof ApiSsoSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/idoru'
    | '/logout'
    | '/media-empire'
    | '/menu'
    | '/api/sso/consume'
    | '/api/sso/login'
    | '/api/sso/logout'
    | '/api/sso/profile'
    | '/api/sso/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/idoru'
    | '/logout'
    | '/media-empire'
    | '/menu'
    | '/api/sso/consume'
    | '/api/sso/login'
    | '/api/sso/logout'
    | '/api/sso/profile'
    | '/api/sso/session'
  id:
    | '__root__'
    | '/'
    | '/idoru'
    | '/logout'
    | '/media-empire'
    | '/menu'
    | '/api/sso/consume'
    | '/api/sso/login'
    | '/api/sso/logout'
    | '/api/sso/profile'
    | '/api/sso/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdoruRoute: typeof IdoruRoute
  LogoutRoute: typeof LogoutRoute
  MediaEmpireRoute: typeof MediaEmpireRoute
  MenuRoute: typeof MenuRoute
  ApiSsoConsumeRoute: typeof ApiSsoConsumeRoute
  ApiSsoLoginRoute: typeof ApiSsoLoginRoute
  ApiSsoLogoutRoute: typeof ApiSsoLogoutRoute
  ApiSsoProfileRoute: typeof ApiSsoProfileRoute
  ApiSsoSessionRoute: typeof ApiSsoSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idoru': {
      id: '/idoru'
      path: '/idoru'
      fullPath: '/idoru'
      preLoaderRoute: typeof IdoruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-empire': {
      id: '/media-empire'
      path: '/media-empire'
      fullPath: '/media-empire'
      preLoaderRoute: typeof MediaEmpireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso/consume': {
      id: '/api/sso/consume'
      path: '/api/sso/consume'
      fullPath: '/api/sso/consume'
      preLoaderRoute: typeof ApiSsoConsumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso/login': {
      id: '/api/sso/login'
      path: '/api/sso/login'
      fullPath: '/api/sso/login'
      preLoaderRoute: typeof ApiSsoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso/logout': {
      id: '/api/sso/logout'
      path: '/api/sso/logout'
      fullPath: '/api/sso/logout'
      preLoaderRoute: typeof ApiSsoLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso/profile': {
      id: '/api/sso/profile'
      path: '/api/sso/profile'
      fullPath: '/api/sso/profile'
      preLoaderRoute: typeof ApiSsoProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso/session': {
      id: '/api/sso/session'
      path: '/api/sso/session'
      fullPath: '/api/sso/session'
      preLoaderRoute: typeof ApiSsoSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdoruRoute: IdoruRoute,
  LogoutRoute: LogoutRoute,
  MediaEmpireRoute: MediaEmpireRoute,
  MenuRoute: MenuRoute,
  ApiSsoConsumeRoute: ApiSsoConsumeRoute,
  ApiSsoLoginRoute: ApiSsoLoginRoute,
  ApiSsoLogoutRoute: ApiSsoLogoutRoute,
  ApiSsoProfileRoute: ApiSsoProfileRoute,
  ApiSsoSessionRoute: ApiSsoSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
